### ISSUE TITLE
Timestamp for some scheduled games apparently defaulting to midnight EDT

### ISSUE THREAD

**Issue by TeneoPython01** [BlueSCar/cfb-data#5]
Hello!  My apologies in advance if this isn't the correct channel to notify you of what could be a potential timestamp issue with the games data in the collegefootballdata.com api.  

I noticed that on api.collegefootballdata.com the timestamp for the upcoming game for a couple teams appears to be defaulting to midnight eastern time on Saturday.  It's been this way for at least several days.

A couple examples:  
1) Florida State plays Clemson in week 7 (2019 season) on Saturday 10/12 at 2:30pm CDT, but the response body shows the same as item #2 below (Friday night at 11:00pm CDT, which is midnight EDT).
2) Wake Forest plays Louisville in week 7 (2019 season) on Saturday 10/12 at 6:30pm CDT, but the response body shows '2019-10-12T04:00:00.000Z' which translates to Friday night at 11:00pm CDT (midnight EDT).

I suspect this issue might be caused by the fact that both WFU and FSU had bye weeks in week 6.  Perhaps the scraper did not re-scrape after the times for the week 7 games due to something related to the byes?; however, I am only speculating.

Anyway, I just wanted you to be aware of the potential issue.  I love your data set and API, thank you for keeping it open!

**Comment by BlueSCar** [comment]
Yeah, I had a job that would update these as soon as they changed, but then ESPN made some changes that screwed with this piece of functionality, in particular.  Long story short, what was once an automated process is now a manual script that I have to run every week (and I often done remember until someone points it out).

Anyway, weeks 7 and 8 should be up-to-date as of right now., Thanks for the heads up!
